### ISSUE TITLE
FIX: State being regularly sent

### ISSUE THREAD

**Issue by Zakrok09** [delft-hyperloop/Helios_III#48]
If the state is updated post starting of server the GUI stays at initial state until the state is sent. Possibly have the main PCB regularly send the state every 1 second or smt?

@andtsa

**Comment by Zakrok09** [comment]
Also the quit server doesn't seem to do anything. Is it really the case or is there a bug in the GUI?

**Comment by andtsa** [comment]
this is a "feature" of the backend, I need to find a way to propagate thread AbortHandle(s) through nested thread spawns

**Comment by andtsa** [comment]
as for sending state regularly, I currently send it in every state transition. If there's no issue with the frontend losing the state messages later, I can just add one line that sends a state upon connecting with the ground station @Zakrok09
